default_language_version:
  python: python3.10

repos:
  - repo: local
    hooks:
      - id: can-build
        name: can build
        description: Make sure the project can actually be build.
        entry: python -m build
        language: python
        additional_dependencies: [ pip, wheel, build ]
        always_run: true
        require_serial: true
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: pretty-format-json
        args: [ --autofix, --no-ensure-ascii ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ --filter-files ]

  - repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        args: [ --disable=all, --enable=unused-import ]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        args: [ --strict ]
        additional_dependencies: [ types-all, "fastapi[all]" ]
